/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * AnonymousReviewService
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { ListCourseReviewsOutputPayload } from "./models";

export const getListCourseReviewsResponseMock =
	(): ListCourseReviewsOutputPayload =>
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.number.int(),
			comments: faker.string.alpha({ length: { min: 10, max: 20 } }),
			stats: {
				docencia: faker.helpers.arrayElement([
					faker.number.int({ min: 1, max: 5 }),
					undefined,
				]),
				vibes: faker.helpers.arrayElement([
					faker.number.int({ min: 1, max: 5 }),
					undefined,
				]),
				relevancia: faker.helpers.arrayElement([
					faker.number.int({ min: 1, max: 5 }),
					undefined,
				]),
				carga: faker.helpers.arrayElement([
					faker.number.int({ min: 1, max: 5 }),
					undefined,
				]),
				dificultad: faker.helpers.arrayElement([
					faker.number.int({ min: 1, max: 5 }),
					undefined,
				]),
			},
			tags: Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
			created_at: faker.date.past().toISOString().slice(0, 19) + "Z",
		}));

export const getListCourseReviewsMockHandler = (
	overrideResponse?:
		| ListCourseReviewsOutputPayload
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) =>
				| Promise<ListCourseReviewsOutputPayload>
				| ListCourseReviewsOutputPayload),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/courses/:courseCode/reviews",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getListCourseReviewsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};
export const getAnonymousReviewServiceMock = () => [
	getListCourseReviewsMockHandler(),
];
