/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * AnonymousReviewService
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type {
	ListCourseReviewsOutputPayload,
	ListCourseReviewsParams,
} from "./models";

export type listCourseReviewsResponse200 = {
	data: ListCourseReviewsOutputPayload;
	status: 200;
};

export type listCourseReviewsResponseSuccess = listCourseReviewsResponse200 & {
	headers: Headers;
};
export type listCourseReviewsResponse = listCourseReviewsResponseSuccess;

export const getListCourseReviewsUrl = (
	courseCode: string,
	params?: ListCourseReviewsParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/api/courses/${courseCode}/reviews?${stringifiedParams}`
		: `/api/courses/${courseCode}/reviews`;
};

export const listCourseReviews = async (
	courseCode: string,
	params?: ListCourseReviewsParams,
	options?: RequestInit,
): Promise<listCourseReviewsResponse> => {
	const res = await fetch(getListCourseReviewsUrl(courseCode, params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: listCourseReviewsResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as listCourseReviewsResponse;
};

export const getListCourseReviewsQueryKey = (
	courseCode: string,
	params?: ListCourseReviewsParams,
) => {
	return [
		`/api/courses/${courseCode}/reviews`,
		...(params ? [params] : []),
	] as const;
};

export const getListCourseReviewsQueryOptions = <
	TData = Awaited<ReturnType<typeof listCourseReviews>>,
	TError = unknown,
>(
	courseCode: string,
	params?: ListCourseReviewsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listCourseReviews>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getListCourseReviewsQueryKey(courseCode, params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof listCourseReviews>>
	> = ({ signal }) =>
		listCourseReviews(courseCode, params, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: courseCode !== null && courseCode !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof listCourseReviews>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListCourseReviewsQueryResult = NonNullable<
	Awaited<ReturnType<typeof listCourseReviews>>
>;
export type ListCourseReviewsQueryError = unknown;

export function useListCourseReviews<
	TData = Awaited<ReturnType<typeof listCourseReviews>>,
	TError = unknown,
>(
	courseCode: string,
	params: undefined | ListCourseReviewsParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listCourseReviews>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listCourseReviews>>,
					TError,
					Awaited<ReturnType<typeof listCourseReviews>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListCourseReviews<
	TData = Awaited<ReturnType<typeof listCourseReviews>>,
	TError = unknown,
>(
	courseCode: string,
	params?: ListCourseReviewsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listCourseReviews>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listCourseReviews>>,
					TError,
					Awaited<ReturnType<typeof listCourseReviews>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListCourseReviews<
	TData = Awaited<ReturnType<typeof listCourseReviews>>,
	TError = unknown,
>(
	courseCode: string,
	params?: ListCourseReviewsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listCourseReviews>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useListCourseReviews<
	TData = Awaited<ReturnType<typeof listCourseReviews>>,
	TError = unknown,
>(
	courseCode: string,
	params?: ListCourseReviewsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listCourseReviews>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getListCourseReviewsQueryOptions(
		courseCode,
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
