/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * ReviewService
 * OpenAPI spec version: 1.0.0
 */

export interface DuplicatedEntityResponseContent {
	reason: string;
	/** @minItems 1 */
	conflicting_fields: string[];
}
