/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * ReviewService
 * OpenAPI spec version: 1.0.0
 */
import type { Ordering } from "./ordering";

export type ListReviewsParams = {
	course_id?: string;
	account_id?: number;
	/**
	 * @minimum 1
	 * @maximum 50
	 */
	limit?: number;
	after?: number;
	created_order?: Ordering;
};
