/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * ReviewService
 * OpenAPI spec version: 1.0.0
 */

export type Ordering = (typeof Ordering)[keyof typeof Ordering];

export const Ordering = {
	asc: "asc",
	desc: "desc",
} as const;
