/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * ReviewService
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type {
	CreateReviewRequestContent,
	CreateReviewResponseContent,
	GetReviewResponseContent,
	ListReviewsOutputPayload,
	ListReviewsParams,
} from "./models";

export type listReviewsResponse200 = {
	data: ListReviewsOutputPayload;
	status: 200;
};

export type listReviewsResponseSuccess = listReviewsResponse200 & {
	headers: Headers;
};
export type listReviewsResponse = listReviewsResponseSuccess;

export const getListReviewsUrl = (params?: ListReviewsParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/api/reviews?${stringifiedParams}`
		: `/api/reviews`;
};

export const listReviews = async (
	params?: ListReviewsParams,
	options?: RequestInit,
): Promise<listReviewsResponse> => {
	const res = await fetch(getListReviewsUrl(params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: listReviewsResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as listReviewsResponse;
};

export const getListReviewsQueryKey = (params?: ListReviewsParams) => {
	return [`/api/reviews`, ...(params ? [params] : [])] as const;
};

export const getListReviewsQueryOptions = <
	TData = Awaited<ReturnType<typeof listReviews>>,
	TError = unknown,
>(
	params?: ListReviewsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listReviews>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListReviewsQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listReviews>>> = ({
		signal,
	}) => listReviews(params, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listReviews>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListReviewsQueryResult = NonNullable<
	Awaited<ReturnType<typeof listReviews>>
>;
export type ListReviewsQueryError = unknown;

export function useListReviews<
	TData = Awaited<ReturnType<typeof listReviews>>,
	TError = unknown,
>(
	params: undefined | ListReviewsParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listReviews>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listReviews>>,
					TError,
					Awaited<ReturnType<typeof listReviews>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListReviews<
	TData = Awaited<ReturnType<typeof listReviews>>,
	TError = unknown,
>(
	params?: ListReviewsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listReviews>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listReviews>>,
					TError,
					Awaited<ReturnType<typeof listReviews>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListReviews<
	TData = Awaited<ReturnType<typeof listReviews>>,
	TError = unknown,
>(
	params?: ListReviewsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listReviews>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useListReviews<
	TData = Awaited<ReturnType<typeof listReviews>>,
	TError = unknown,
>(
	params?: ListReviewsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listReviews>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getListReviewsQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type createReviewResponse200 = {
	data: CreateReviewResponseContent;
	status: 200;
};

export type createReviewResponseSuccess = createReviewResponse200 & {
	headers: Headers;
};
export type createReviewResponse = createReviewResponseSuccess;

export const getCreateReviewUrl = () => {
	return `/api/reviews`;
};

export const createReview = async (
	createReviewRequestContent: CreateReviewRequestContent,
	options?: RequestInit,
): Promise<createReviewResponse> => {
	const res = await fetch(getCreateReviewUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(createReviewRequestContent),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: createReviewResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as createReviewResponse;
};

export const getCreateReviewMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createReview>>,
		TError,
		{ data: CreateReviewRequestContent },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createReview>>,
	TError,
	{ data: CreateReviewRequestContent },
	TContext
> => {
	const mutationKey = ["createReview"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createReview>>,
		{ data: CreateReviewRequestContent }
	> = (props) => {
		const { data } = props ?? {};

		return createReview(data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateReviewMutationResult = NonNullable<
	Awaited<ReturnType<typeof createReview>>
>;
export type CreateReviewMutationBody = CreateReviewRequestContent;
export type CreateReviewMutationError = unknown;

export const useCreateReview = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createReview>>,
			TError,
			{ data: CreateReviewRequestContent },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createReview>>,
	TError,
	{ data: CreateReviewRequestContent },
	TContext
> => {
	return useMutation(getCreateReviewMutationOptions(options), queryClient);
};

export type getReviewResponse200 = {
	data: GetReviewResponseContent;
	status: 200;
};

export type getReviewResponseSuccess = getReviewResponse200 & {
	headers: Headers;
};
export type getReviewResponse = getReviewResponseSuccess;

export const getGetReviewUrl = (reviewId: number) => {
	return `/api/reviews/${reviewId}`;
};

export const getReview = async (
	reviewId: number,
	options?: RequestInit,
): Promise<getReviewResponse> => {
	const res = await fetch(getGetReviewUrl(reviewId), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getReviewResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getReviewResponse;
};

export const getGetReviewQueryKey = (reviewId: number) => {
	return [`/api/reviews/${reviewId}`] as const;
};

export const getGetReviewQueryOptions = <
	TData = Awaited<ReturnType<typeof getReview>>,
	TError = unknown,
>(
	reviewId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getReview>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetReviewQueryKey(reviewId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getReview>>> = ({
		signal,
	}) => getReview(reviewId, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: reviewId !== null && reviewId !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getReview>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetReviewQueryResult = NonNullable<
	Awaited<ReturnType<typeof getReview>>
>;
export type GetReviewQueryError = unknown;

export function useGetReview<
	TData = Awaited<ReturnType<typeof getReview>>,
	TError = unknown,
>(
	reviewId: number,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getReview>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getReview>>,
					TError,
					Awaited<ReturnType<typeof getReview>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReview<
	TData = Awaited<ReturnType<typeof getReview>>,
	TError = unknown,
>(
	reviewId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getReview>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getReview>>,
					TError,
					Awaited<ReturnType<typeof getReview>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReview<
	TData = Awaited<ReturnType<typeof getReview>>,
	TError = unknown,
>(
	reviewId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getReview>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetReview<
	TData = Awaited<ReturnType<typeof getReview>>,
	TError = unknown,
>(
	reviewId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getReview>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetReviewQueryOptions(reviewId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
