/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * ReviewService
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type {
	CreateReviewResponseContent,
	GetReviewResponseContent,
	ListReviewsOutputPayload,
} from "./models";

export const getListReviewsResponseMock = (): ListReviewsOutputPayload =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.number.int(),
		account_id: faker.number.int(),
		course_code: faker.string.alpha({ length: { min: 10, max: 20 } }),
		comments: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		stats: {
			docencia: faker.helpers.arrayElement([
				faker.number.int({ min: 1, max: 5 }),
				undefined,
			]),
			vibes: faker.helpers.arrayElement([
				faker.number.int({ min: 1, max: 5 }),
				undefined,
			]),
			relevancia: faker.helpers.arrayElement([
				faker.number.int({ min: 1, max: 5 }),
				undefined,
			]),
			carga: faker.helpers.arrayElement([
				faker.number.int({ min: 1, max: 5 }),
				undefined,
			]),
			dificultad: faker.helpers.arrayElement([
				faker.number.int({ min: 1, max: 5 }),
				undefined,
			]),
		},
		tags: Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
		created_at: faker.date.past().toISOString().slice(0, 19) + "Z",
	}));

export const getCreateReviewResponseMock = (
	overrideResponse: Partial<Extract<CreateReviewResponseContent, object>> = {},
): CreateReviewResponseContent => ({
	id: faker.number.int(),
	account_id: faker.number.int(),
	course_code: faker.string.alpha({ length: { min: 10, max: 20 } }),
	comments: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	stats: {
		docencia: faker.helpers.arrayElement([
			faker.number.int({ min: 1, max: 5 }),
			undefined,
		]),
		vibes: faker.helpers.arrayElement([
			faker.number.int({ min: 1, max: 5 }),
			undefined,
		]),
		relevancia: faker.helpers.arrayElement([
			faker.number.int({ min: 1, max: 5 }),
			undefined,
		]),
		carga: faker.helpers.arrayElement([
			faker.number.int({ min: 1, max: 5 }),
			undefined,
		]),
		dificultad: faker.helpers.arrayElement([
			faker.number.int({ min: 1, max: 5 }),
			undefined,
		]),
	},
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
	created_at: faker.date.past().toISOString().slice(0, 19) + "Z",
	...overrideResponse,
});

export const getGetReviewResponseMock = (
	overrideResponse: Partial<Extract<GetReviewResponseContent, object>> = {},
): GetReviewResponseContent => ({
	id: faker.number.int(),
	account_id: faker.number.int(),
	course_code: faker.string.alpha({ length: { min: 10, max: 20 } }),
	comments: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	stats: {
		docencia: faker.helpers.arrayElement([
			faker.number.int({ min: 1, max: 5 }),
			undefined,
		]),
		vibes: faker.helpers.arrayElement([
			faker.number.int({ min: 1, max: 5 }),
			undefined,
		]),
		relevancia: faker.helpers.arrayElement([
			faker.number.int({ min: 1, max: 5 }),
			undefined,
		]),
		carga: faker.helpers.arrayElement([
			faker.number.int({ min: 1, max: 5 }),
			undefined,
		]),
		dificultad: faker.helpers.arrayElement([
			faker.number.int({ min: 1, max: 5 }),
			undefined,
		]),
	},
	tags: Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
	created_at: faker.date.past().toISOString().slice(0, 19) + "Z",
	...overrideResponse,
});

export const getListReviewsMockHandler = (
	overrideResponse?:
		| ListReviewsOutputPayload
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<ListReviewsOutputPayload> | ListReviewsOutputPayload),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/reviews",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getListReviewsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getCreateReviewMockHandler = (
	overrideResponse?:
		| CreateReviewResponseContent
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<CreateReviewResponseContent> | CreateReviewResponseContent),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/api/reviews",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getCreateReviewResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getGetReviewMockHandler = (
	overrideResponse?:
		| GetReviewResponseContent
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<GetReviewResponseContent> | GetReviewResponseContent),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/reviews/:reviewId",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetReviewResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};
export const getReviewServiceMock = () => [
	getListReviewsMockHandler(),
	getCreateReviewMockHandler(),
	getGetReviewMockHandler(),
];
