/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * CourseService
 * OpenAPI spec version: 1.0.0
 */
import type { CourseStat } from "./courseStat";

export interface CourseTagStats {
	[key: string]: CourseStat;
}
