/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * CourseService
 * OpenAPI spec version: 1.0.0
 */

export * from "./course";
export * from "./courseStat";
export * from "./courseStats";
export * from "./courseTagStats";
export * from "./getCourseResponseContent";
export * from "./listCoursesOutputPayload";
export * from "./listCoursesParams";
