/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * CourseService
 * OpenAPI spec version: 1.0.0
 */

export type ListCoursesParams = {
	/**
	 * @minimum 1
	 * @maximum 50
	 */
	limit?: number;
	after?: string;
};
