/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * CourseService
 * OpenAPI spec version: 1.0.0
 */
import type { Course } from "./course";

export type ListCoursesOutputPayload = Course[];
