/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * AnonymousReviewService
 * OpenAPI spec version: 1.0.0
 */

export type ListCourseReviewsParams = {
	/**
	 * @minimum 1
	 * @maximum 50
	 */
	limit?: number;
	after?: number;
};
