/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * AuthenticationService
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type {
	DccLoginParams,
	DccLoginResponseContent,
	PasswordLoginRequestContent,
	PasswordLoginResponseContent,
} from "./models";

export type dccLoginResponse200 = {
	data: DccLoginResponseContent;
	status: 200;
};

export type dccLoginResponseSuccess = dccLoginResponse200 & {
	headers: Headers;
};
export type dccLoginResponse = dccLoginResponseSuccess;

export const getDccLoginUrl = (params: DccLoginParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/api/workflow/login/dcc?${stringifiedParams}`
		: `/api/workflow/login/dcc`;
};

export const dccLogin = async (
	params: DccLoginParams,
	options?: RequestInit,
): Promise<dccLoginResponse> => {
	const res = await fetch(getDccLoginUrl(params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: dccLoginResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as dccLoginResponse;
};

export const getDccLoginQueryKey = (params?: DccLoginParams) => {
	return [`/api/workflow/login/dcc`, ...(params ? [params] : [])] as const;
};

export const getDccLoginQueryOptions = <
	TData = Awaited<ReturnType<typeof dccLogin>>,
	TError = unknown,
>(
	params: DccLoginParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof dccLogin>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getDccLoginQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof dccLogin>>> = ({
		signal,
	}) => dccLogin(params, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof dccLogin>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DccLoginQueryResult = NonNullable<
	Awaited<ReturnType<typeof dccLogin>>
>;
export type DccLoginQueryError = unknown;

export function useDccLogin<
	TData = Awaited<ReturnType<typeof dccLogin>>,
	TError = unknown,
>(
	params: DccLoginParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof dccLogin>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof dccLogin>>,
					TError,
					Awaited<ReturnType<typeof dccLogin>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDccLogin<
	TData = Awaited<ReturnType<typeof dccLogin>>,
	TError = unknown,
>(
	params: DccLoginParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof dccLogin>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof dccLogin>>,
					TError,
					Awaited<ReturnType<typeof dccLogin>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDccLogin<
	TData = Awaited<ReturnType<typeof dccLogin>>,
	TError = unknown,
>(
	params: DccLoginParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof dccLogin>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useDccLogin<
	TData = Awaited<ReturnType<typeof dccLogin>>,
	TError = unknown,
>(
	params: DccLoginParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof dccLogin>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getDccLoginQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type passwordLoginResponse200 = {
	data: PasswordLoginResponseContent;
	status: 200;
};

export type passwordLoginResponseSuccess = passwordLoginResponse200 & {
	headers: Headers;
};
export type passwordLoginResponse = passwordLoginResponseSuccess;

export const getPasswordLoginUrl = () => {
	return `/api/workflow/login/pass`;
};

export const passwordLogin = async (
	passwordLoginRequestContent: PasswordLoginRequestContent,
	options?: RequestInit,
): Promise<passwordLoginResponse> => {
	const res = await fetch(getPasswordLoginUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(passwordLoginRequestContent),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: passwordLoginResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as passwordLoginResponse;
};

export const getPasswordLoginMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof passwordLogin>>,
		TError,
		{ data: PasswordLoginRequestContent },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof passwordLogin>>,
	TError,
	{ data: PasswordLoginRequestContent },
	TContext
> => {
	const mutationKey = ["passwordLogin"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof passwordLogin>>,
		{ data: PasswordLoginRequestContent }
	> = (props) => {
		const { data } = props ?? {};

		return passwordLogin(data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PasswordLoginMutationResult = NonNullable<
	Awaited<ReturnType<typeof passwordLogin>>
>;
export type PasswordLoginMutationBody = PasswordLoginRequestContent;
export type PasswordLoginMutationError = unknown;

export const usePasswordLogin = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof passwordLogin>>,
			TError,
			{ data: PasswordLoginRequestContent },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof passwordLogin>>,
	TError,
	{ data: PasswordLoginRequestContent },
	TContext
> => {
	return useMutation(getPasswordLoginMutationOptions(options), queryClient);
};
