/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * AccountService
 * OpenAPI spec version: 1.0.0
 */
import type { AccountRole } from "./accountRole";

export interface CreateAccountRequestContent {
	username: string;
	password: string;
	role: AccountRole;
	name: string;
}
