/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * AuthenticationService
 * OpenAPI spec version: 1.0.0
 */

export interface PasswordLoginRequestContent {
	username: string;
	password: string;
}
