/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MallaRouteImport } from './routes/malla'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CursoCursoIdRouteImport } from './routes/curso/$cursoId'

const MallaRoute = MallaRouteImport.update({
  id: '/malla',
  path: '/malla',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursoCursoIdRoute = CursoCursoIdRouteImport.update({
  id: '/curso/$cursoId',
  path: '/curso/$cursoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/malla': typeof MallaRoute
  '/curso/$cursoId': typeof CursoCursoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/malla': typeof MallaRoute
  '/curso/$cursoId': typeof CursoCursoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/malla': typeof MallaRoute
  '/curso/$cursoId': typeof CursoCursoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/malla' | '/curso/$cursoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/malla' | '/curso/$cursoId'
  id: '__root__' | '/' | '/admin' | '/malla' | '/curso/$cursoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  MallaRoute: typeof MallaRoute
  CursoCursoIdRoute: typeof CursoCursoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/malla': {
      id: '/malla'
      path: '/malla'
      fullPath: '/malla'
      preLoaderRoute: typeof MallaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curso/$cursoId': {
      id: '/curso/$cursoId'
      path: '/curso/$cursoId'
      fullPath: '/curso/$cursoId'
      preLoaderRoute: typeof CursoCursoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  MallaRoute: MallaRoute,
  CursoCursoIdRoute: CursoCursoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
